export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_ERR = "ADMIN_REGISTER_ERR";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERR = "ADMIN_LOGIN_ERR";


// userRegister
export const ADMIN_USER_REGISTER_REQUEST = "ADMIN_USER_REGISTER_REQUEST";
export const ADMIN_USER_REGISTER_SUCCESS = "ADMIN_USER_REGISTER_SUCCESS";
export const ADMIN_USER_REGISTER_ERR = "ADMIN_USER_REGISTER_ERR";


// userFind
export const ADMIN_USER_FIND_REQUEST = "ADMIN_USER_FIND_REQUEST";
export const ADMIN_USER_FIND_SUCCESS = "ADMIN_USER_FIND_SUCCESS";
export const ADMIN_USER_FIND_ERR = "ADMIN_USER_FIND_ERR";


// documentUpload
export const ADMIN_DOCUMENT_ADD_REQUEST = "ADMIN_DOCUMENT_ADD_REQUEST";
export const ADMIN_DOCUMENT_ADD_SUCCESS = "ADMIN_DOCUMENT_ADD_SUCCESS";
export const ADMIN_DOCUMENT_ADD_ERR = "ADMIN_DOCUMENT_ADD_ERR";

// driveDocumentUpload
export const ADMIN_DRIVE_DOCUMENT_ADD_REQUEST = "ADMIN_DRIVE_DOCUMENT_ADD_REQUEST";
export const ADMIN_DRIVE_DOCUMENT_ADD_SUCCESS = "ADMIN_DRIVE_DOCUMENT_ADD_SUCCESS";
export const ADMIN_DRIVE_DOCUMENT_ADD_ERR = "ADMIN_DRIVE_DOCUMENT_ADD_ERR";

// driveDocumentFind
export const ADMIN_DRIVE_DOCUMENT_FIND_REQUEST = "ADMIN_DRIVE_DOCUMENT_FIND_REQUEST";
export const ADMIN_DRIVE_DOCUMENT_FIND_SUCCESS = "ADMIN_DRIVE_DOCUMENT_FIND_SUCCESS";
export const ADMIN_DRIVE_DOCUMENT_FIND_ERR = "ADMIN_DRIVE_DOCUMENT_FIND_ERR";

// documentFind
export const ADMIN_DOCUMENT_FIND_REQUEST = "ADMIN_DOCUMENT_FIND_REQUEST";
export const ADMIN_DOCUMENT_FIND_SUCCESS = "ADMIN_DOCUMENT_FIND_SUCCESS";
export const ADMIN_DOCUMENT_FIND_ERR = "ADMIN_DOCUMENT_FIND_ERR";


// documentFind
export const ADMIN_DOCUMENT_VID_DELETE_REQUEST = "ADMIN_DOCUMENT_VID_DELETE_REQUEST";
export const ADMIN_DOCUMENT_VID_DELETE_SUCCESS = "ADMIN_DOCUMENT_VID_DELETE_SUCCESS";
export const ADMIN_DOCUMENT_VID_DELETE_ERR = "ADMIN_DOCUMENT_VID_DELETE_ERR";

// deleteDriveDocu
export const ADMIN_DOCUMENT_DRIVE_DELETE_REQUEST = "ADMIN_DOCUMENT_DRIVE_DELETE_REQUEST";
export const ADMIN_DOCUMENT_DRIVE_DELETE_SUCCESS = "ADMIN_DOCUMENT_DRIVE_DELETE_SUCCESS";
export const ADMIN_DOCUMENT_DRIVE_DELETE_ERR = "ADMIN_DOCUMENT_DRIVE_DELETE_ERR";