export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_ERR = "ADMIN_REGISTER_ERR";

export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_ERR = "ADMIN_LOGIN_ERR";

// userRegister
export const ADMIN_USER_REGISTER_REQUEST = "ADMIN_USER_REGISTER_REQUEST";
export const ADMIN_USER_REGISTER_SUCCESS = "ADMIN_USER_REGISTER_SUCCESS";
export const ADMIN_USER_REGISTER_ERR = "ADMIN_USER_REGISTER_ERR";

// userFind
export const ADMIN_USER_FIND_REQUEST = "ADMIN_USER_FIND_REQUEST";
export const ADMIN_USER_FIND_SUCCESS = "ADMIN_USER_FIND_SUCCESS";
export const ADMIN_USER_FIND_ERR = "ADMIN_USER_FIND_ERR";

// documentUpload
export const ADMIN_DOCUMENT_ADD_REQUEST = "ADMIN_DOCUMENT_ADD_REQUEST";
export const ADMIN_DOCUMENT_ADD_SUCCESS = "ADMIN_DOCUMENT_ADD_SUCCESS";
export const ADMIN_DOCUMENT_ADD_ERR = "ADMIN_DOCUMENT_ADD_ERR";

// driveDocumentUpload
export const ADMIN_DRIVE_DOCUMENT_ADD_REQUEST =
  "ADMIN_DRIVE_DOCUMENT_ADD_REQUEST";
export const ADMIN_DRIVE_DOCUMENT_ADD_SUCCESS =
  "ADMIN_DRIVE_DOCUMENT_ADD_SUCCESS";
export const ADMIN_DRIVE_DOCUMENT_ADD_ERR = "ADMIN_DRIVE_DOCUMENT_ADD_ERR";

// driveDocumentFind
export const ADMIN_DRIVE_DOCUMENT_FIND_REQUEST =
  "ADMIN_DRIVE_DOCUMENT_FIND_REQUEST";
export const ADMIN_DRIVE_DOCUMENT_FIND_SUCCESS =
  "ADMIN_DRIVE_DOCUMENT_FIND_SUCCESS";
export const ADMIN_DRIVE_DOCUMENT_FIND_ERR = "ADMIN_DRIVE_DOCUMENT_FIND_ERR";

// documentFind
export const ADMIN_DOCUMENT_FIND_REQUEST = "ADMIN_DOCUMENT_FIND_REQUEST";
export const ADMIN_DOCUMENT_FIND_SUCCESS = "ADMIN_DOCUMENT_FIND_SUCCESS";
export const ADMIN_DOCUMENT_FIND_ERR = "ADMIN_DOCUMENT_FIND_ERR";

// documentFind
export const ADMIN_DOCUMENT_VID_DELETE_REQUEST =
  "ADMIN_DOCUMENT_VID_DELETE_REQUEST";
export const ADMIN_DOCUMENT_VID_DELETE_SUCCESS =
  "ADMIN_DOCUMENT_VID_DELETE_SUCCESS";
export const ADMIN_DOCUMENT_VID_DELETE_ERR = "ADMIN_DOCUMENT_VID_DELETE_ERR";

// deleteDriveDocu
export const ADMIN_DOCUMENT_DRIVE_DELETE_REQUEST =
  "ADMIN_DOCUMENT_DRIVE_DELETE_REQUEST";
export const ADMIN_DOCUMENT_DRIVE_DELETE_SUCCESS =
  "ADMIN_DOCUMENT_DRIVE_DELETE_SUCCESS";
export const ADMIN_DOCUMENT_DRIVE_DELETE_ERR =
  "ADMIN_DOCUMENT_DRIVE_DELETE_ERR";

// userStatusChange
export const USER_STATUS_CHANGE_REQUEST = "USER_STATUS_CHANGE_REQUEST";
export const USER_STATUS_CHANGE_SUCCESS = "USER_STATUS_CHANGE_SUCCESS";
export const USER_STATUS_CHANGE_ERR = "USER_STATUS_CHANGE_ERR";

// AdminFind
export const ADMIN_FIND_REQUEST = "ADMIN_FIND_REQUEST";
export const ADMIN_FIND_SUCCESS = "ADMIN_FIND_SUCCESS";
export const ADMIN_FIND_ERR = "ADMIN_FIND_ERR";

// searchForMessage
export const SEARCH_FOR_MESSAGE_REQUEST = "SEARCH_FOR_MESSAGE_REQUEST";
export const SEARCH_FOR_MESSAGE_SUCCESS = "SEARCH_FOR_MESSAGE_SUCCESS";
export const SEARCH_FOR_MESSAGE_ERR = "SEARCH_FOR_MESSAGE_ERR";

// chatStarClickt
export const CHAT_START_CLICK_REQUEST = "CHAT_START_CLICK_REQUEST";
export const CHAT_START_CLICK_SUCCESS = "CHAT_START_CLICK_SUCCESS";
export const CHAT_START_CLICK_ERR = "CHAT_START_CLICK_ERR";

// submitNewMessage
export const SUBMIT_NEW_MESSAGE_REQUEST = "SUBMIT_NEW_MESSAGE_REQUEST";
export const SUBMIT_NEW_MESSAGE_SUCCESS = "SUBMIT_NEW_MESSAGE_SUCCESS";
export const SUBMIT_NEW_MESSAGE_ERR = "SUBMIT_NEW_MESSAGE_ERR";

// \chatShow
export const CHAT_SHOW_SECTION_REQUEST = "CHAT_SHOW_SECTION_REQUEST";
export const CHAT_SHOW_SECTION_SUCCESS = "CHAT_SHOW_SECTION_SUCCESS";
export const CHAT_SHOW_SECTION_ERR = "CHAT_SHOW_SECTION_ERR";

// \userMsgToAdminAction socket-io
export const USER_MSG_TOADMIN_REQUEST = "USER_MSG_TOADMIN_REQUEST";
export const USER_MSG_TOADMIN_SUCCESS = "USER_MSG_TOADMIN_SUCCESS";
export const USER_MSG_TOADMIN_ERR = "USER_MSG_TOADMIN_ERR";
