// findUserVideoLink
export const USER_VIDEO_LINK_FIND_REQUEST = "USER_VIDEO_LINK_FIND_REQUEST";
export const USER_VIDEO_LINK_FIND_SUCCESS = "USER_VIDEO_LINK_FIND_SUCCESS";
export const USER_VIDEO_LINK_FIND_ERR = "USER_VIDEO_LINK_FIND_ERR";

// findUserDocumentLink
export const USER_DOCUMENT_LINK_FIND_REQUEST =
  "USER_DOCUMENT_LINK_FIND_REQUEST";
export const USER_DOCUMENT_LINK_FIND_SUCCESS =
  "USER_DOCUMENT_LINK_FIND_SUCCESS";
export const USER_DOCUMENT_LINK_FIND_ERR = "USER_DOCUMENT_LINK_FIND_ERR";

// userChatFind
export const USER_CHAT_FIND_REQUEST = "USER_CHAT_FIND_REQUEST";
export const USER_CHAT_FIND_SUCCESS = "USER_CHAT_FIND_SUCCESS";
export const USER_CHAT_FIND_ERR = "USER_CHAT_FIND_ERR";

// userChatSubmit
export const USER_CHAT_SUBMIT_REQUEST = "USER_CHAT_SUBMIT_REQUEST";
export const USER_CHAT_SUBMIT_SUCCESS = "USER_CHAT_SUBMIT_SUCCESS";
export const USER_CHAT_SUBMIT_ERR = "USER_CHAT_SUBMIT_ERR";

// userChatSubmit
export const ADMIN_SEARCH_SOCKET_REQUEST = "ADMIN_SEARCH_SOCKET_REQUEST";
export const ADMIN_SEARCH_SOCKET_SUCCESS = "ADMIN_SEARCH_SOCKET_SUCCESS";
export const ADMIN_SEARCH_SOCKET_ERR = "ADMIN_SEARCH_SOCKET_ERR";
