// findUserVideoLink
export const USER_VIDEO_LINK_FIND_REQUEST = "USER_VIDEO_LINK_FIND_REQUEST";
export const USER_VIDEO_LINK_FIND_SUCCESS = "USER_VIDEO_LINK_FIND_SUCCESS";
export const USER_VIDEO_LINK_FIND_ERR = "USER_VIDEO_LINK_FIND_ERR";

// findUserDocumentLink
export const USER_DOCUMENT_LINK_FIND_REQUEST = "USER_DOCUMENT_LINK_FIND_REQUEST";
export const USER_DOCUMENT_LINK_FIND_SUCCESS = "USER_DOCUMENT_LINK_FIND_SUCCESS";
export const USER_DOCUMENT_LINK_FIND_ERR = "USER_DOCUMENT_LINK_FIND_ERR";